import { Aboreto, EB_Garamond, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toolbar } from "@mui/material";

const aboreto = Aboreto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-heading",
});

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-body",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Sky Dance Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${aboreto.variable} ${ebGaramond.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="font-body">
        <Navbar />
        <Toolbar sx={{ display: { xs: "none", sm: "block" } }} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
