import { Aboreto, EB_Garamond } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toolbar } from "@mui/material";
import Footer from "@/components/Footer";

const aboreto = Aboreto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-heading",
});

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata = {
  title: "Sky Dance Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${aboreto.variable} ${ebGaramond.variable}`}>
      <body className="font-body">
        <Navbar />
        <Toolbar />
        <Toolbar />
        {children}
      </body>
      <Footer />
    </html>
  );
}
